<a href="https://colab.research.google.com/github/coder7475/fiveFunctionsOfTorchTensor/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Torch Tesors

An short introduction about PyTorch and about the chosen functions. 

- torch.zeros() : This function creates a tensor filled with zeros of the specified shape.
- torch.randn() : This function creates a tensor with random values drawn from a normal deistribution with mean 0 and standard deviation 1.
- torch.matmul() : This function performs a matrix multiplication between two tensors.
- torch.reshape() : This function reshapes the input tesor to the specified shape.
- torch.flatten() : This function flattens the input tensor into a 1D tensor.

Before we begin, let's install and import PyTorch

In [2]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [3]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros()

This function creates a tensor filled with zeros of the specified shape.


In [4]:
# Example 1 - working
torch.zeros((3, 5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In example 1, a tensor of shape (3, 5) is created with all elements initialized to zero.

In [5]:
# Example 2 - working
torch.zeros((4, 2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In example 2, a tensor of shape (4, 2) is created with all elements initialized to zero.

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
torch.zeros()

TypeError: ignored

Expample 3 trys to fill a empty array with 0 which is why it gives a TypeError.

This Function is useful in many data science projects when you need to create a tensor of a specific shape initialized with zeros.

Let's save our work using Jovian before continuing.

## Function 2 - torch.randn()

This function creates a tensor with random values drawn from a normal distribution with mean 0 and standard deviation 1.

In [7]:
# Example 1 - working
torch.randn((4, 4))

tensor([[ 0.2627, -0.3272, -0.0163,  1.7083],
        [-0.6777, -0.1015,  0.4302,  1.0329],
        [-2.0548, -0.8586, -1.4865, -0.9326],
        [ 0.7799,  0.6487,  0.4323,  1.7019]])

In this example, a tensor shape (4, 4) is created with random values.

In [8]:
# Example 2 - working
torch.randn((4, 3))

tensor([[-1.3583, -0.9506, -0.4950],
        [-1.0086,  0.6357,  0.1155],
        [ 0.4143,  0.1556, -0.4676],
        [-0.7013, -0.3064,  0.0903]])

Here, a tensor of shpape (4, 3) is created with random values.

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
torch.randn(1.23)

TypeError: ignored

In this example Shape of tesor need to be tuples of ints but given a float value.

This function is often used in deep learning projects for weight initialization and regulization.

## Function 3 - torch.matmul()

This function performs matrix multiplication between two tensors.

In [10]:
# Example 1 - working
a = torch.randn((4, 3))
b = torch.randn((3, 2))
torch.matmul(a, b)

tensor([[-3.3543,  0.3336],
        [-1.3575,  6.1866],
        [-0.2338,  2.8811],
        [ 0.3537, -0.2714]])

In this example two tensors named a and b of shape (4,3) and (3, 2) are multiplied together. The resultant matrix has shape of (4, 2).

In [11]:
# Example 2 - working
a = torch.randn((4,3))# Matrix
b = torch.randn(3)    # vector
torch.matmul(a, b)

tensor([-0.9768, -0.2104, -0.0859,  0.9662])

Here the multifplication of a matrix of shape (4,3) and a vector of size 3 results in a vector of size 4.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.randn((3, 3))
b = torch.randn((2, 1))
torch.matmul(a, b)

RuntimeError: ignored

Here two matrix of shape (3, 3) and (2, 1) are mutliplied which gives a runtime error because for matrix multiplication the column of first matrix and and row of second matrix must be equal.

This function is a powerful and flexible function in PyTorch that is extensively used in deep learning for various operations such as forward and backward propagation, weight and bias updates, convolutional and recurrent neural networks, and more.

## Function 4 - torch.reshape()

This function reshapes the input tesor to the specified shape.

In [13]:
# Example 1 - working
a = torch.randn((4, 3))
torch.reshape(a, (3, -1))

tensor([[ 0.1383, -0.3997,  0.1032,  1.1597],
        [-0.8116,  0.5966, -1.7798,  0.0667],
        [-0.8857,  0.2838, -0.0849,  0.2494]])

In this example, the tensor a is reshaped to have three rows and an unspecified number of column. The -1 value in the shape argument is a placeholder that automatically calculates the size of the dimension based on the other dimensions and the total number of elements in the tensor.

In [14]:
# Example 2 - working
a = torch.randn((2, 3))
torch.reshape(a, (3, 2))

tensor([[-0.9533, -1.4351],
        [-0.3352, -0.4955],
        [ 1.0287, -1.9411]])

This example reshapes a matrix of (2, 3) to a matrix of (3, 2)

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.rand((2, 3))
torch.reshape((3, 3))

TypeError: ignored

Here, I attempted to create a matrix of shape (3, 3) which contains 9 elements from a matrix of shape (2, 3) which contains 6 elements. So Error is encountered. 

This function is extensively used in deep learning to transform tensors into a desired shape for operations such as convolution, pooling, and fully connected layers, among others.

## Function 5 - torch.flatten()

This function flattens the input tensor into a 1D tensor.

In [16]:
# Example 1 - working
a = torch.randn((4, 3))
torch.flatten(a)

tensor([ 1.0586,  0.2678, -0.1304,  0.9654, -0.5981, -0.0049,  0.9271, -1.3041,
        -0.8031,  0.2778,  0.5288, -0.5108])

Here a 2D tensor of shape (4, 3) is flattented into a 1D tensor having 12 elements.

In [20]:
# Example 2 - working
a = torch.randn((3, 3))
torch.flatten(a, start_dim=0, end_dim=-1)

tensor([ 1.3269,  2.6867, -0.3765, -1.1772, -1.4655, -0.1247,  0.1677,  0.7923,
        -1.6569])

In this example, the tensor a is flattened from the start_dim=0 (the first dimension) to the end_dim=-1 (the last dimension). From a 2D shape (3, 3) to 1D of shape (9).

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.randn((3, 3))
torch.flatten(a, start_dim=3, end_dim=-1)

IndexError: ignored

n this example, we attempt to flatten the 2D tensor a with a start_dim argument of 3, which is higher than the tensor's number of dimensions. This results in an IndexError.

This function is extensively used in deep learning to convert multi-dimensional tensors into one-dimensional tensors, which can be fed into fully connected layers or other neural network layers that require a flattened input.

Here is a summary of the PyTorch functions discussed in this notebook:

    torch.zeros(): A function that creates a tensor of a specified shape filled with zeros.
    torch.randn(): A function that creates a tensor of a specified shape with random values drawn from a normal distribution with mean 0 and standard deviation 1.
    torch.matmul(): A function that performs matrix multiplication between two tensors.
    torch.reshape(): A function that reshapes a tensor into a new shape without changing its data.
    torch.flatten(): A function that flattens a tensor into a one-dimensional tensor.

All of these functions are extensively used in deep learning for various operations such as initialization, matrix multiplication, reshaping, and flattening of tensors.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* PyTorch tutorials: https://pytorch.org/tutorials/
* PyTorch Examples: https://pytorch.org/examples/