<a href="https://colab.research.google.com/github/coder7475/fiveFunctionsOfTorchTensor/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Torch Tesors

An short introduction about PyTorch and about the chosen functions. 

- torch.zeros() : This function creates a tensor filled with zeros of the specified shape.
- torch.randn() : This function creates a tensor with random values drawn from a normal deistribution with mean 0 and standard deviation 1.
- torch.matmul() : This function performs a matrix multiplication between two tensors.
- torch.reshape() : This function reshapes the input tesor to the specified shape.
- torch.flatten() : This function flattens the input tensor into a 1D tensor.

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros()

This function creates a tensor filled with zeros of the specified shape.


In [3]:
# Example 1 - working
torch.zeros((3, 5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In example 1, a tensor of shape (3, 5) is created with all elements initialized to zero.

In [6]:
# Example 2 - working
torch.zeros((4, 2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In example 2, a tensor of shape (4, 2) is created with all elements initialized to zero.

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
torch.zeros()

TypeError: ignored

Expample 3 trys to fill a empty array with 0 which is why it gives a TypeError.

This Function is useful in many data science projects when you need to create a tensor of a specific shape initialized with zeros.

Let's save our work using Jovian before continuing.

## Function 2 - torch.randn()

This function creates a tensor with random values drawn from a normal distribution with mean 0 and standard deviation 1.

In [20]:
# Example 1 - working
torch.randn((4, 4))

tensor([[-0.2629,  1.0485,  0.3187, -1.0942],
        [-0.6173, -0.6386,  0.7828,  0.7727],
        [-0.1490,  0.9426, -1.2021,  0.8269],
        [ 1.0487, -0.6626,  0.7998, -1.1054]])

In this example, a tensor shape (4, 4) is created with random values.

In [21]:
# Example 2 - working
torch.randn((4, 3))

tensor([[ 0.0478,  0.2495,  0.9985],
        [ 1.3603,  0.5119, -0.5067],
        [-1.7654,  0.3457,  0.1056],
        [ 0.6270, -0.8147, -0.1929]])

Here, a tensor of shpape (4, 3) is created with random values.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
torch.randn(1.23)

TypeError: ignored

In this example Shape of tesor need to be tuples of ints but given a float value.

This function is often used in deep learning projects for weight initialization and regulization.

## Function 3 - torch.matmul()

This function performs matrix multiplication between two tensors.

In [27]:
# Example 1 - working
a = torch.randn((4, 3))
b = torch.randn((3, 2))
torch.matmul(a, b)

tensor([[ 0.8512, -0.1629],
        [ 0.5089, -0.2365],
        [ 1.0314,  1.4040],
        [-0.7301,  0.6238]])

In this example two tensors named a and b of shape (4,3) and (3, 2) are multiplied together. The resultant matrix has shape of (4, 2).

In [31]:
# Example 2 - working
a = torch.randn((4,3))# Matrix
b = torch.randn(3)    # vector
torch.matmul(a, b)

tensor([ 2.0412,  1.3988, -2.0763,  1.3492])

Here the multifplication of a matrix of shape (4,3) and a vector of size 3 results in a vector of size 4.

In [34]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.randn((3, 3))
b = torch.randn((2, 1))
torch.matmul(a, b)

RuntimeError: ignored

Here two matrix of shape (3, 3) and (2, 1) are mutliplied which gives a runtime error because for matrix multiplication the column of first matrix and and row of second matrix must be equal.

This function is a powerful and flexible function in PyTorch that is extensively used in deep learning for various operations such as forward and backward propagation, weight and bias updates, convolutional and recurrent neural networks, and more.

## Function 4 - torch.reshape()

This function reshapes the input tesor to the specified shape.

In [42]:
# Example 1 - working
a = torch.randn((4, 3))
torch.reshape(a, (3, -1))

tensor([[-0.3809, -0.5245, -0.5867, -0.0291],
        [ 0.0980,  1.1443, -0.0651, -0.1208],
        [-1.0731, -1.5821,  0.1728,  0.3317]])

Explanation about example

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working

Explanation about example

In [ ]:
# Example 2 - working

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
